# Generated by Django 2.2.5 on 2020-01-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '测试团队'},
        ),
        migrations.AlterModelTable(
            name='projects',
            table='tb_projects',
        ),
    ]
