# Generated by Django 2.2.5 on 2020-01-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_views', '0002_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(help_text='项目名称', max_length=200, verbose_name='项目名称'),
        ),
    ]
