# Generated by Django 2.2.5 on 2020-01-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_auto_20200122_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interfaces',
            options={'verbose_name': '测试团队'},
        ),
        migrations.AlterModelTable(
            name='interfaces',
            table='tb_interfaces',
        ),
    ]
