# Generated by Django 2.2.5 on 2020-01-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0003_auto_20200122_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaces',
            name='leader',
        ),
    ]
