# Generated by Django 2.2.5 on 2020-01-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0004_remove_interfaces_leader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interfaces',
            options={'verbose_name': '接口'},
        ),
    ]
