# Generated by Django 2.2.5 on 2020-01-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200122_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '项目'},
        ),
    ]
