# Generated by Django 2.2.5 on 2020-01-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='项目名称', max_length=200, verbose_name='项目名称')),
                ('leader', models.CharField(help_text='项目负责人', max_length=50, verbose_name='项目负责人')),
                ('tester', models.CharField(help_text='测试人员', max_length=50, verbose_name='测试人员')),
                ('programmer', models.CharField(help_text='开发人员', max_length=50, verbose_name='开发人员')),
                ('publish_app', models.CharField(help_text='发布应用', max_length=100, verbose_name='发布应用')),
                ('desc', models.CharField(blank=True, default='', help_text='简要描述', max_length=200, null=True, verbose_name='简要描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='TestTeam',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='团队名称', max_length=200, verbose_name='团队名称')),
                ('leader', models.CharField(help_text='负责人', max_length=50, verbose_name='负责人')),
                ('tester', models.CharField(help_text='测试人员', max_length=50, verbose_name='测试人员')),
                ('modulename', models.CharField(help_text='模块名称', max_length=200, verbose_name='模块名称')),
                ('desc', models.CharField(blank=True, default='', help_text='简要描述', max_length=200, null=True, verbose_name='简要描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
        ),
    ]
