# Generated by Django 2.2.5 on 2020-01-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_views', '0006_auto_20200121_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='testteam',
            name='group_leader',
            field=models.CharField(default=1, help_text='小组长', max_length=50, unique=True, verbose_name='小组长'),
            preserve_default=False,
        ),
    ]
