# Generated by Django 2.2.5 on 2020-01-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_views', '0007_testteam_group_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='testteam',
            name='review_time',
            field=models.DateTimeField(auto_now=True, help_text='审核时间', verbose_name='审核时间'),
        ),
    ]
