# Generated by Django 2.2.5 on 2020-01-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_views', '0002_auto_20200117_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testteam',
            name='name',
            field=models.CharField(help_text='团队名称', max_length=200, unique=True, verbose_name='团队名称'),
        ),
    ]
