# Generated by Django 2.2.5 on 2020-01-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_views', '0003_auto_20200117_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testteam',
            options={'verbose_name': '测试团队'},
        ),
        migrations.AlterModelTable(
            name='testteam',
            table='TestTeams',
        ),
    ]
