# Generated by Django 2.2.5 on 2020-01-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_views', '0004_auto_20200120_2340'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testteam',
            table='django_views_TestTeams',
        ),
    ]
