# Generated by Django 2.2.5 on 2020-01-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_views', '0005_auto_20200120_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testteam',
            old_name='modulename',
            new_name='module_name',
        ),
    ]
